### ISSUE TITLE
请问后面的笔记还更新吗

### ISSUE THREAD

**Issue by ToDuan** [xxuanzhu/convex-optimization#1]

**Comment by xxuanzhu** [comment]
还会更新的，最近有点忙...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhuxx-Sage/convex-optimization"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 晚上10:37
收件人:&nbsp;"Zhuxx-Sage/convex-optimization"<convex-optimization@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhuxx-Sage/convex-optimization] 请问后面的笔记还更新吗 (#1)





 
Closed #1.
